### ISSUE TITLE
How do you build this

### ISSUE THREAD

**Issue by TheMaskedMan00** [imhunterand/easy-bypass#1]
There's no project file nor is there any build instructions

**Comment by imhunterand** [comment]
what you mean ? this is a project for bypassing eac
you can find here https://github.com/imhunterand/easy-bypass/find/main

**Comment by SussyImp0ster** [comment]
How do you actually install this and where? There's no executable file anywhere or instructions

**Comment by imhunterand** [comment]
**Hi!** @SussyImp0ster 

This project is published and used for people who understand the progress of the source build! but not for children who are just waiting for the `.exe` file from the finished build ^_^
