### ISSUE TITLE
say goodbye

### ISSUE THREAD

**Issue by moongazer07** [imhunterand/easy-bypass#3]
i reported it so soon it will no longer work lol

**Comment by imhunterand** [comment]
your mouth, your Tiger

**Comment by iFlxy** [comment]
Am I the only here desparate to play a game I like under Linux?

**Comment by imhunterand** [comment]
@iFlxy don't despair brother there is still supermario

**Comment by iFlxy** [comment]
> @iFlxy don't despair brother there is still supermario

why so rude lol

**Comment by fwflunky** [comment]
is that still working?
